-- MySQL Script generated by MySQL Workbench
-- Tue Feb  5 11:32:57 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema RackaKey
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema RackaKey
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `RackaKey` DEFAULT CHARACTER SET utf8 ;
USE `RackaKey` ;

-- -----------------------------------------------------
-- Table `RackaKey`.`UsbKeys`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RackaKey`.`UsbKeys` (
  `idUsbKeys` INT NOT NULL,
  `name` VARCHAR(60) NULL,
  `hub` INT NULL,
  `hubPort` INT NULL,
  PRIMARY KEY (`idUsbKeys`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
